#!/usr/bin/env bash
# build-images.sh — responsive image variants + the srcset that uses them.
#
# WHY
# Every photo on this site was a single 1024×1024 file being drawn into slots
# between 340 px and 650 px wide. The text on the page weighs ~63 KB compressed;
# the pictures weigh ~470 KB. That is where the weight actually is.
#
# The width that matters most is 720: a phone at devicePixelRatio 2 drawing a
# 364 px slot needs 728 px, so it was being handed the full 1024 px file. With a
# 720 variant present the browser takes that instead — roughly half the bytes on
# the device we care about most (a customer in Addis on mobile data).
#
# WHAT IT DOES
#   1. for every img/*.jpg master → writes  img/<name>-400.{webp,jpg}
#                                            img/<name>-720.{webp,jpg}
#   2. rewrites every <picture> block in index.html and every product page so
#      the <source> carries srcset + sizes
#   3. updates the hero preload so the LCP image is not fetched twice
#
# Deterministic, no network, no compilation. ImageMagick + cwebp only, both of
# which are on this phone. Re-run it whenever the photographs change.
#
# RUN:  bash build-images.sh
set -euo pipefail
cd "$(dirname "$0")"

WIDTHS="400 720"
MASTER_SUFFIX=".jpg"

echo "── 1. variants ────────────────────────────────────────────"
for src in img/*"$MASTER_SUFFIX"; do
  name="$(basename "$src" "$MASTER_SUFFIX")"
  case "$name" in *-400|*-720|og-card) continue;; esac
  for w in $WIDTHS; do
    # jpg fallback for browsers/paths without WebP (and for the og/social scrapers)
    magick "$src" -resize "${w}x${w}" -strip -quality 78 "img/${name}-${w}.jpg"
    # webp is what almost every visitor actually gets
    cwebp -quiet -q 80 -resize "$w" "$w" "$src" -o "img/${name}-${w}.webp"
  done
  printf "  %-12s %6s → %6s / %6s KB\n" "$name" \
    "$(( $(stat -c%s "$src") / 1024 ))" \
    "$(( $(stat -c%s "img/${name}-400.webp") / 1024 ))" \
    "$(( $(stat -c%s "img/${name}-720.webp") / 1024 ))"
done

echo "── 2. markup ──────────────────────────────────────────────"
python3 - <<'PY'
import io, re, glob, os

# One shared `sizes` for grid imagery. Checked against the real layout:
#   ≤860px   every tile is one column          → 100vw - 48 (the .wrap gutter)
#   ≤1024px  three tiles per row               → ~34vw
#   wider    the big tile is 650px, the small ones ~433 → 46vw picks 720 for both
GRID_SIZES = "(max-width: 860px) calc(100vw - 48px), (max-width: 1024px) 34vw, 46vw"
HERO_SIZES = "(max-width: 860px) 100vw, 50vw"
PROD_SIZES = "(max-width: 920px) calc(100vw - 48px), 880px"

def srcset(name, ext, base="img"):
    return "%s/%s-400.%s 400w, %s/%s-720.%s 720w, %s/%s.%s 1024w" % (
        base, name, ext, base, name, ext, base, name, ext)

def sizes_for(name, hero=False, prod=False):
    if hero: return HERO_SIZES
    if prod: return PROD_SIZES
    return GRID_SIZES

def rewrite(html, prod=False):
    # <source type="image/webp" srcset="img/x.webp">  →  + srcset list + sizes
    def fix_source(m):
        src = m.group(2)
        name, ext = src.rsplit("/", 1)[1].rsplit(".", 1)
        root = src.rsplit("/", 1)[0]
        sizes = sizes_for(name, prod=prod)
        return '%s%s srcset="%s" sizes="%s"%s' % (
            m.group(1), src, srcset(name, ext, root), sizes, m.group(3))
    html = re.sub(r'(<source type="image/webp" srcset=")([^"]+)("[^>]*>)', fix_source, html)

    # <img src="img/x.jpg" ...>  →  add srcset + sizes (keeps width/height)
    def fix_img(m):
        tag = m.group(0)
        if 'srcset=' in tag: return tag
        srcm = re.search(r'src="([^"]+)"', tag)
        src = srcm.group(1)
        name, ext = src.rsplit("/", 1)[1].rsplit(".", 1)
        root = src.rsplit("/", 1)[0]
        hero = 'fetchpriority="high"' in tag
        sizes = sizes_for(name, hero=hero, prod=prod)
        return tag.replace(srcm.group(0),
            '%s srcset="%s" sizes="%s"' % (srcm.group(0), srcset(name, ext, root), sizes))
    html = re.sub(r'<img[^>]*src="(?:img|/img)/[^"]+"[^>]*>', fix_img, html)
    return html

# index.html is hand-maintained so it is patched here. The product pages are
# GENERATED by build-pages.js — their srcset lives in the generator, because
# patching generated output is undone by the next regeneration.
for f in ["index.html"]:
    s = io.open(f, encoding="utf-8").read()
    out = rewrite(s)
    if out != s:
        io.open(f, "w", encoding="utf-8").write(out)
        print("  ✓ %s" % f)

# hero preload must name the same candidate list, or the browser fetches the
# 1024 file for the preload and then the 400 for the render: two downloads
idx = io.open("index.html", encoding="utf-8").read()
old = '<link rel="preload" as="image" href="img/photobook.webp" type="image/webp">'
new = ('<link rel="preload" as="image" href="img/photobook-720.webp" type="image/webp"\n'
       '      imagesrcset="%s"\n      imagesizes="%s">' % (srcset("photobook", "webp"), HERO_SIZES))
if old in idx:
    io.open("index.html", "w", encoding="utf-8").write(idx.replace(old, new))
    print("  ✓ hero preload now carries imagesrcset")

# the LCP image must not be lazy
idx = io.open("index.html", encoding="utf-8").read()
before = idx
idx = idx.replace('<img src="img/photobook.jpg" alt="Hardcover photo book',
                  '<img src="img/photobook.jpg" fetchpriority="high" alt="Hardcover photo book')
if idx != before:
    io.open("index.html", "w", encoding="utf-8").write(idx)
    print("  ✓ hero image marked fetchpriority=high")
PY

echo "── 3. totals ──────────────────────────────────────────────"
printf "  masters (1024): %6s KB\n" "$(( $(cat img/canvas.webp img/calendar.webp img/flatlay.webp img/frames.webp img/mug.webp img/photobook.webp | wc -c) / 1024 ))"
printf "  variants add  : %6s KB on disk (never all downloaded at once)\n" \
  "$(( $(cat img/*-400.webp img/*-720.webp img/*-400.jpg img/*-720.jpg 2>/dev/null | wc -c) / 1024 ))"
echo "  done — now run:  node build-pages.js && node pagetest.js && node domtest.js"
